name: Update repo list

on:
  push:
    branches: 
      - main
  schedule:
    - cron: "0 0 */3 * *" # run every 3 days at 00:00

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
 
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
 
    - name: Format code
      run: black it_club_update.py
 
    - name: Run the script to update repo list
      run: python it_club_update.py
 
    - name: Commit updated file(s) back to this repository
      run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git diff-index --quiet HEAD || git commit -m "[update] Save updated repo list"
          git fetch
          git push
