name: Update repo list

on:
  push:
    branches: 
      - main
  schedule:
    - cron: "0 */12 * * *" # run every 12 hours

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
 
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
 
    - name: Format code
      run: black it_club_update.py
 
    - name: Run the script to update repo list
      run: python it_club_update.py
 
    - name: Commit updated file(s) back to this repository
      run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git diff-index --quiet HEAD || git commit -m "[skip ci] Save result of action"
          git fetch
          git push
